test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/ps/data/zidongcao/Dataset/lau_dataset/odisr/testing/LR/X16
      root_path_2: /home/ps/data/zidongcao/Dataset/lau_dataset/odisr/testing/HR
  wrapper:
    name: sr-paired
    args: {}
  batch_size: 1
eval_type: osr-16

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}